version: '2'
template:
  name: "Finance Trade"
  description: "FinTrade is a modern finance portfolio manager that provides real-time insight into how news all around the world can impact the investment to any given portfolio."
  required:
    - build
    - repo

toolchain:
  name: 'finance-trade-{{timestamp}}'

services:
  repo:
    service_id: githubpublic
    parameters:
      repo_name: 'finance-trade'
      repo_url: 'https://github.com/IBM-Bluemix/finance-trade'
      type: fork
      has_issues: false
  build:
    service_id: pipeline
    parameters:
      services:
        - repo
      name: '{{services.repo.parameters.repo_name}}'
      ui-pipeline: true
      configuration:
        content:
          $text: pipeline.yml
        env:
          REPO: repo
          REPO_BRANCH: '{{form.pipeline.parameters.app-branch-name}}'
          CF_APP_NAME: 'fintrade'
          SPACE_NAME: '{{form.pipeline.parameters.app-space}}'
          ORG_NAME: '{{form.pipeline.parameters.app-organization}}'
          REGION_ID: '{{form.pipeline.parameters.app-region}}'
        execute: true

form:
  pipeline:
    parameters:
      app-branch-name: "master"
    schema:
      $ref: deploy.json
